baseURL: "https://jmautomas.my"
languageCode: "en-us"
title: "Proton"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxxx-x
disqusShortname: yourdisqusname
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

    

params:
  favicon: "logo.png"
  description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2021"


  show: true
  netlify: false
  action: ""
  method: "POST"
  section: "Contact me!"
  disclaimer: "Contact Us"
  inputNameName: "electricMing"
  inputNameLabel: "Name"
  inputNamePlaceholder: "Your Name"
  inputEmailName: "electricGod"
  inputEmailLabel: "Email"
  inputEmailPlaceholder: "Your Email"
  inputPhoneName: "electricTalk"
  inputPhoneLabel: "Phone"
  inputPhonePlaceholder: "Your Phone"
  SubmitValue: "Submit"

  # Navbar Menus
  customMenus:
  # - name: "Blog"
  #   Url: "/blog"
    
  # social
  name: "Hugo-profile"
  github: "https://github.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com"
  instagram: "https://instagram.com"
  facebook: "https://facebook.com"

  # About
  profile_image: ""
  descripe_l1_person: "A high performance hugo theme for personal website and blog. It is a single page portfolio."
  descripe_l2_person: "This is just a example for about section. You can easily change with the help of cofig file."
  job: "Your job"
  useresume: true
  resume: ""

  Images:
    - image: 1
      

    - image: 2
      

    - image: 3
      
  # Things I do
  usedothings: true
  Things:
    - logo: fab fa-python
      title: Python
      description: I build something beautiful using Python.

    - logo: fas fa-robot
      title:  Machine learning 
      description: I train robust models for various tasks. 

    - logo: fab fa-html5
      title: Things for web 
      description: I love to build things for web

  #blog ( Description for seo. If you want to show description in your blog post, let's make it true)
  showdescription: true

Author:
  name: "Gurusabarish"
  website: "https://github.com/gurusabarish"